const PDFDocument = require('pdfkit');
require('dotenv').config();

const { Resend } = require('resend');
const resend = new Resend(process.env.RESEND_API_KEY);

const sendEmail = async (mailOptions) => {
  return resend.emails.send({
    from: process.env.EMAIL_FROM || 'SchoolMS <onboarding@resend.dev>',
    to: mailOptions.to,
    subject: mailOptions.subject,
    html: mailOptions.html,
    attachments: mailOptions.attachments?.map(a => ({
      filename: a.filename,
      content: a.content,
    }))
  });
};

// HELPER LOGIC: STRICT INDIA LOCAL TIME CAPTURE OVERRIDE FOR CLOUD CHIPS
const getIndiaDateTimeString = () => {
  return new Date().toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    hour12: true
  });
};

// ─── GENERATE FEE RECEIPT PDF BUFFER ─────────────────────────
const generateFeeReceiptPDFBuffer = (receipt) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A5', margin: 40 });
    const buffers = [];
    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);
    doc.rect(0, 0, doc.page.width, 80).fill('#1e40af');
    doc.fillColor('white').fontSize(18).font('Helvetica-Bold').text('SchoolMS', 40, 20);
    doc.fontSize(10).font('Helvetica').text('Fee Payment Receipt', 40, 44);
    doc.fontSize(9).text(`Receipt No: ${receipt.receipt_no}`, 40, 58);
    doc.text(`Date: ${receipt.payment_date?.split('T')[0] || ''}`, 40, 70);
    doc.fillColor('#1e293b').fontSize(11).font('Helvetica-Bold').text('Payment Details', 40, 100);
    const rows = [
      ['Student Name', receipt.full_name || '—'],
      ['Roll No', receipt.roll_no || '—'],
      ['Class', receipt.class_name || '—'],
      ['Fee Type', receipt.fee_type_name || '—'],
      ['Payment Month', receipt.payment_month || '—'],
      ['Payment Method', receipt.payment_method || 'Cash'],
      ['Remarks', receipt.remarks || '—'],
    ];
    let y = 118;
    rows.forEach(([label, value], i) => {
      if (i % 2 === 0) doc.rect(40, y, doc.page.width - 80, 22).fill('#f8fafc');
      doc.fillColor('#64748b').fontSize(9).font('Helvetica-Bold').text(label, 48, y + 6, { width: 120 });
      doc.fillColor('#1e293b').font('Helvetica').text(String(value), 175, y + 6, { width: 160 });
      y += 22;
    });
    y += 10;
    doc.rect(40, y, doc.page.width - 80, 50).fill('#f0fdf4').stroke('#16a34a');
    doc.fillColor('#16a34a').fontSize(16).font('Helvetica-Bold')
      .text(`Rs. ${parseFloat(receipt.amount || 0).toLocaleString('en-IN')}`, 40, y + 10, { align: 'center', width: doc.page.width - 80 });
    doc.fontSize(9).font('Helvetica').fillColor('#64748b')
      .text('Amount Received', 40, y + 32, { align: 'center', width: doc.page.width - 80 });
    y += 70;
    doc.fillColor('#94a3b8').fontSize(8)
      .text('Thank you for your payment • Generated by SchoolMS', 40, y, { align: 'center', width: doc.page.width - 80 });
    doc.end();
  });
};

// ─── GENERATE SALARY SLIP PDF BUFFER ─────────────────────────
const generateSalarySlipPDFBuffer = (slip) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A5', margin: 40 });
    const buffers = [];
    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);
    const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    const monthLabel = slip.month ? (() => {
      const parts = slip.month.split('-');
      return `${monthNames[parseInt(parts[1]) - 1]} ${parts[0]}`;
    })() : slip.month;
    doc.rect(0, 0, doc.page.width, 80).fill('#1e40af');
    doc.fillColor('white').fontSize(18).font('Helvetica-Bold').text('SchoolMS', 40, 20);
    doc.fontSize(10).font('Helvetica').text('Salary Slip', 40, 44);
    doc.fontSize(9).text(`Slip No: ${slip.slip_no}`, 40, 58);
    doc.text(`Month: ${monthLabel}`, 40, 70);
    doc.fillColor('#1e293b').fontSize(11).font('Helvetica-Bold').text('Employee Details', 40, 100);
    const empRows = [
      ['Employee Name', slip.full_name || '—'],
      ['Employee ID', slip.emp_id || '—'],
      ['Designation', slip.role_name || '—'],
      ['Month', monthLabel],
    ];
    let y = 118;
    empRows.forEach(([label, value], i) => {
      if (i % 2 === 0) doc.rect(40, y, doc.page.width - 80, 22).fill('#f8fafc');
      doc.fillColor('#64748b').fontSize(9).font('Helvetica-Bold').text(label, 48, y + 6, { width: 120 });
      doc.fillColor('#1e293b').font('Helvetica').text(String(value), 175, y + 6, { width: 160 });
      y += 22;
    });
    y += 12;
    doc.fillColor('#1e293b').fontSize(11).font('Helvetica-Bold').text('Salary Breakdown', 40, y);
    y += 18;
    doc.rect(40, y, doc.page.width - 80, 22).fill('#1e40af');
    doc.fillColor('white').fontSize(9).font('Helvetica-Bold')
      .text('Component', 48, y + 6, { width: 120 })
      .text('Amount', 175, y + 6, { width: 140, align: 'right' });
    y += 22;
    const salaryRows = [
      ['Basic Salary', `Rs. ${parseFloat(slip.basic_salary || 0).toLocaleString('en-IN')}`],
      ['Deductions', `- Rs. ${parseFloat(slip.deductions || 0).toLocaleString('en-IN')}`],
      ['Net Salary', `Rs. ${parseFloat(slip.net_salary || 0).toLocaleString('en-IN')}`],
    ];
    salaryRows.forEach(([label, value], i) => {
      const isNet = i === 2;
      doc.rect(40, y, doc.page.width - 80, 24).fill(isNet ? '#f0fdf4' : (i % 2 === 0 ? '#f8fafc' : 'white'));
      doc.fillColor(isNet ? '#16a34a' : '#1e293b')
        .fontSize(isNet ? 10 : 9)
        .font(isNet ? 'Helvetica-Bold' : 'Helvetica')
        .text(label, 48, y + 7, { width: 120 })
        .text(value, 175, y + 7, { width: 140, align: 'right' });
      y += 24;
    });
    y += 10;
    const isPaid = slip.status === 'paid';
    doc.rect(40, y, doc.page.width - 80, 28)
      .fill(isPaid ? '#f0fdf4' : '#fef3c7')
      .stroke(isPaid ? '#16a34a' : '#f59e0b');
    const statusLabel = slip.status === 'paid' ? 'DEPOSITED' : 'GENERATED';
    doc.fillColor(isPaid ? '#16a34a' : '#d97706')
      .fontSize(10).font('Helvetica-Bold')
      .text(`Status: ${statusLabel}`, 40, y + 9, { align: 'center', width: doc.page.width - 80 });
    y += 45;
    doc.fillColor('#94a3b8').fontSize(8).font('Helvetica')
      .text('Generated by SchoolMS • Computer Generated Document', 40, y, { align: 'center', width: doc.page.width - 80 });
    doc.end();
  });
};

// ─── SEND PASSWORD RESET EMAIL ────────────────────────────────
const sendPasswordResetEmail = async (toEmail, userName, otp) => {
  return sendEmail({
    to: toEmail,
    subject: `${otp} is your SchoolMS Password Reset OTP`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);">
        <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;font-weight:800;">SchoolMS</h1>
          <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">Password Reset OTP</p>
        </div>
        <div style="padding:32px;text-align:center;">
          <p style="font-size:15px;color:#1e293b;">Hello <strong>${userName}</strong>,</p>
          <p style="font-size:14px;color:#64748b;">Use the OTP below to reset your password:</p>
          <div style="background:#f0f9ff;border:3px solid #1e40af;border-radius:14px;padding:24px;margin:24px 0;">
            <div style="font-size:48px;font-weight:900;letter-spacing:12px;color:#1e40af;font-family:monospace;">${otp}</div>
          </div>
          <p style="font-size:13px;color:#64748b;">Valid for <strong>15 minutes</strong> only.</p>
          <p style="font-size:12px;color:#ef4444;">Do NOT share this OTP with anyone.</p>
        </div>
        <div style="background:#f8fafc;padding:16px;text-align:center;border-top:1px solid #e2e8f0;">
          <p style="margin:0;font-size:11px;color:#94a3b8;">SchoolMS Automated Notification</p>
        </div>
      </div>`
  });
};

// ─── SEND PASSWORD CHANGED EMAIL ──────────────────────────────
const sendPasswordChangedEmail = async (toEmail, userName) => {
  return sendEmail({
    to: toEmail,
    subject: 'SchoolMS - Password Changed Successfully',
    html: `
      <div style="font-family:Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#059669,#10b981);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;">Password Changed</h1>
        </div>
        <div style="padding:28px;">
          <p>Hello <strong>${userName}</strong>,</p>
          <p style="color:#64748b;">Your SchoolMS password has been changed successfully.</p>
          <p style="color:#64748b;">If you did not do this, contact your administrator immediately.</p>
          <p style="color:#64748b;">Time: <strong>${getIndiaDateTimeString()}</strong></p>
        </div>
      </div>`
  });
};

// ─── SEND ATTENDANCE NOTIFICATION ────────────────────────────
// ─── SEND ATTENDANCE NOTIFICATION (UPDATED FOR DYNAMIC STUDENT/EMPLOYEE SWITCH) ───
const sendAttendanceNotification = async (toEmail, parentOrRoleName, personName, classNameOrDept, date, status) => {
  const statusDetails = {
    present: { emoji: '✅', color: '#16a34a', bg: '#f0fdf4', text: 'PRESENT' },
    absent:  { emoji: '❌', color: '#dc2626', bg: '#fef2f2', text: 'ABSENT'  },
    late:    { emoji: '⏰', color: '#d97706', bg: '#fffbeb', text: 'LATE'    },
    halfday: { emoji: '🌓', color: '#7c3aed', bg: '#faf5ff', text: 'HALF DAY'},
  };
  const d = statusDetails[status] || statusDetails.present;

  // ─── NEW ADD-ON: DYNAMIC LABELS SWITCH BASED ON THE RECEIPENT TYPE ───
  // Agar classNameOrDept 'Staff Management' hai, iska matlab yeh notification ek employee ke liye hai
  const isEmployee = classNameOrDept === 'Staff Management';
  
  const greetingText = isEmployee 
    ? `Dear <strong>${personName}</strong>,` 
    : `Dear <strong>Parent/Guardian</strong>,`;

  const dynamicHeaderSentence = isEmployee
    ? `You are ${d.text} today`
    : `${personName} is ${d.text} today`;

  const dynamicTypeLabel = isEmployee ? 'Employee' : 'Student';
  const dynamicGroupLabel = isEmployee ? 'Department' : 'Class';

  return sendEmail({
    to: toEmail,
    subject: isEmployee 
      ? `${d.emoji} Attendance Alert: You are marked ${d.text} - ${date}`
      : `${d.emoji} Attendance: ${personName} is ${d.text} - ${date}`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.05);">
        <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:24px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:20px;font-weight:800;">SchoolMS</h1>
          <p style="margin:4px 0 0;font-size:12px;opacity:0.8;">Attendance Notification</p>
        </div>
        <div style="padding:24px;text-align:center;">
          <div style="font-size:48px;margin-bottom:8px;">${d.emoji}</div>
          
          <p style="font-size:15px;color:#1e293b;text-align:left;margin-bottom:12px;">${greetingText}</p>
          
          <div style="background:${d.bg};border-radius:10px;padding:16px;margin:16px 0;">
            <div style="font-size:18px;font-weight:800;color:${d.color};">${dynamicHeaderSentence}</div>
          </div>
          
          <table style="width:100%;border-collapse:collapse;text-align:left;margin-top:20px;">
            <tr>
              <td style="padding:10px 8px;color:#94a3b8;font-weight:bold;font-size:13px;width:35%;">${dynamicTypeLabel}</td>
              <td style="padding:10px 8px;font-weight:600;color:#1e293b;font-size:13px;">${personName}</td>
            </tr>
            <tr style="background:#f8fafc;">
              <td style="padding:10px 8px;color:#94a3b8;font-weight:bold;font-size:13px;">${dynamicGroupLabel}</td>
              <td style="padding:10px 8px;font-weight:600;color:#1e293b;font-size:13px;">${classNameOrDept}</td>
            </tr>
            <tr>
              <td style="padding:10px 8px;color:#94a3b8;font-weight:bold;font-size:13px;">Date</td>
              <td style="padding:10px 8px;font-weight:600;color:#1e293b;font-size:13px;">${date}</td>
            </tr>
            <tr style="background:#f8fafc;">
              <td style="padding:10px 8px;color:#94a3b8;font-weight:bold;font-size:13px;">Status</td>
              <td style="padding:10px 8px;font-weight:600;color:${d.color};font-size:13px;">${d.text}</td>
            </tr>
          </table>
        </div>
        <div style="background:#f8fafc;padding:14px;text-align:center;border-top:1px solid #e2e8f0;">
          <p style="margin:0;font-size:11px;color:#94a3b8;">SchoolMS Automated Notification</p>
        </div>
      </div>`
  });
};

// ─── SEND FEE PAYMENT EMAIL WITH PDF ─────────────────────────
const sendFeePaymentNotification = async (toEmail, receipt) => {
  try {
    const pdfBuffer = await generateFeeReceiptPDFBuffer(receipt);
    return sendEmail({
      to: toEmail,
      subject: `Fee Payment Receipt - ${receipt.receipt_no} | ${receipt.full_name}`,
      html: `
        <div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
          <div style="background:linear-gradient(135deg,#059669,#10b981);padding:28px;text-align:center;color:#fff;">
            <h1 style="margin:0;font-size:22px;font-weight:800;">SchoolMS</h1>
            <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">Fee Payment Confirmation</p>
          </div>
          <div style="padding:28px;">
            <p>Dear <strong>Parent/Guardian</strong>,</p>
            <p style="color:#64748b;">Fee payment received. Receipt attached.</p>
            <div style="text-align:center;margin:20px 0;">
              <div style="font-size:36px;font-weight:900;color:#16a34a;">Rs. ${parseFloat(receipt.amount || 0).toLocaleString('en-IN')}</div>
            </div>
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="padding:8px;color:#94a3b8;font-weight:bold;">Student</td><td style="padding:8px;">${receipt.full_name}</td></tr>
              <tr style="background:#f8fafc;"><td style="padding:8px;color:#94a3b8;font-weight:bold;">Class</td><td style="padding:8px;">${receipt.class_name}</td></tr>
              <tr><td style="padding:8px;color:#94a3b8;font-weight:bold;">Fee Type</td><td style="padding:8px;">${receipt.fee_type_name}</td></tr>
              <tr style="background:#f8fafc;"><td style="padding:8px;color:#94a3b8;font-weight:bold;">Date</td><td style="padding:8px;">${receipt.payment_date?.split('T')[0]}</td></tr>
            </table>
          </div>
        </div>`,
      attachments: [{ filename: `Fee-Receipt-${receipt.receipt_no}.pdf`, content: pdfBuffer, contentType: 'application/pdf' }]
    });
  } catch (err) {
    console.error('Fee email error:', err.message);
    throw err;
  }
};

// ─── SEND SALARY SLIP EMAIL WITH PDF ─────────────────────────
const sendSalarySlipNotification = async (toEmail, slip) => {
  try {
    const pdfBuffer = await generateSalarySlipPDFBuffer(slip);
    const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    const monthLabel = slip.month ? (() => {
      const parts = slip.month.split('-');
      return `${monthNames[parseInt(parts[1]) - 1]} ${parts[0]}`;
    })() : slip.month;
    return sendEmail({
      to: toEmail,
      subject: `Salary Slip - ${monthLabel} | ${slip.full_name}`,
      html: `
        <div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
          <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:28px;text-align:center;color:#fff;">
            <h1 style="margin:0;font-size:22px;font-weight:800;">SchoolMS</h1>
            <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">Salary Slip - ${monthLabel}</p>
          </div>
          <div style="padding:28px;">
            <p>Dear <strong>${slip.full_name}</strong>,</p>
            <p style="color:#64748b;">Your salary slip for <strong>${monthLabel}</strong> is attached.</p>
            <div style="text-align:center;margin:20px 0;">
              <div style="font-size:36px;font-weight:900;color:#16a34a;">Rs. ${parseFloat(slip.net_salary || 0).toLocaleString('en-IN')}</div>
              <div style="font-size:12px;color:#64748b;">Net Salary</div>
            </div>
          </div>
        </div>`,
      attachments: [{ filename: `Salary-Slip-${slip.slip_no}-${slip.month}.pdf`, content: pdfBuffer, contentType: 'application/pdf' }]
    });
  } catch (err) {
    console.error('Salary email error:', err.message);
    throw err;
  }
};

// ─── SEND BROADCAST EMAIL ─────────────────────────────────────
const sendBroadcastEmail = async (toEmail, toName, title, message, senderName) => {
  const formattedMessage = message.replace(/\n/g, '<br/>');
  return sendEmail({
    to: toEmail,
    subject: `📢 ${title} — SchoolMS`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;font-weight:800;">🏫 SchoolMS</h1>
        </div>
        <div style="padding:28px;">
          <p style="font-size:16px;font-weight:800;">${title}</p>
          <p>Dear <strong>${toName}</strong>,</p>
          <div style="background:#f8fafc;border-radius:10px;padding:20px;margin:16px 0;">${formattedMessage}</div>
          <p style="font-size:12px;color:#94a3b8;">Sent by <strong>${senderName}</strong></p>
        </div>
      </div>`
  });
};

// ─── WELCOME EMPLOYEE EMAIL ───────────────────────────────────
const sendEmployeeWelcomeEmail = async (toEmail, empName, empId, loginUserId, role, password) => {
  if (!toEmail) return;
  return sendEmail({
    to: toEmail,
    subject: `Welcome to SchoolMS — Your Account is Ready`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;font-weight:800;">🏫 SchoolMS</h1>
          <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">Welcome to the Team!</p>
        </div>
        <div style="padding:28px;">
          <p>Dear <strong>${empName}</strong>,</p>
          <table style="width:100%;border-collapse:collapse;">
            <tr><td style="padding:8px;color:#64748b;font-weight:bold;">Employee ID</td><td style="padding:8px;font-weight:700;color:#1e40af;">${empId}</td></tr>
            <tr style="background:#f8fafc;"><td style="padding:8px;color:#64748b;font-weight:bold;">Login User ID</td><td style="padding:8px;">${loginUserId}</td></tr>
            <tr><td style="padding:8px;color:#64748b;font-weight:bold;">Role</td><td style="padding:8px;">${role}</td></tr>
            <tr style="background:#f8fafc;"><td style="padding:8px;color:#64748b;font-weight:bold;">Password</td><td style="padding:8px;color:#dc2626;font-weight:700;">${password}</td></tr>
          </table>
          <p style="color:#ef4444;font-size:13px;margin-top:16px;">⚠️ Please change your password after first login.</p>
        </div>
      </div>`
  });
};

// ─── EMPLOYEE UPDATE EMAIL ────────────────────────────────────
const sendEmployeeUpdateEmail = async (toEmail, empName) => {
  if (!toEmail) return;
  return sendEmail({
    to: toEmail,
    subject: `SchoolMS — Your Profile Has Been Updated`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;font-weight:800;">🏫 SchoolMS</h1>
        </div>
        <div style="padding:28px;">
          <p>Dear <strong>${empName}</strong>,</p>
          <p style="color:#64748b;">Your student profile has been updated. Time: <strong>${getIndiaDateTimeString()}</strong></p>
        </div>
      </div>`
  });
};

// ─── WELCOME STUDENT EMAIL ────────────────────────────────────
const sendStudentWelcomeEmail = async (toEmail, studentName, rollNo, className) => {
  if (!toEmail) return;
  return sendEmail({
    to: toEmail,
    subject: `Welcome to SchoolMS — Student Enrollment Confirmed`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#059669,#10b981);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;font-weight:800;">🏫 SchoolMS</h1>
          <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">Welcome, New Student!</p>
        </div>
        <div style="padding:28px;">
          <p>Dear <strong>${studentName}</strong>,</p>
          <table style="width:100%;border-collapse:collapse;">
            <tr><td style="padding:8px;color:#64748b;font-weight:bold;">Roll No</td><td style="padding:8px;font-weight:700;color:#059669;">${rollNo}</td></tr>
            <tr style="background:#f8fafc;"><td style="padding:8px;color:#64748b;font-weight:bold;">Class</td><td style="padding:8px;font-weight:700;">${className}</td></tr>
          </table>
        </div>
      </div>`
  });
};

// ─── STUDENT UPDATE EMAIL ─────────────────────────────────────
const sendStudentUpdateEmail = async (toEmail, studentName) => {
  if (!toEmail) return;
  return sendEmail({
    to: toEmail,
    subject: `SchoolMS — Your Profile Has Been Updated`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#059669,#10b981);padding:28px;text-align:center;color:#fff;">
          <h1 style="margin:0;font-size:22px;font-weight:800;">🏫 SchoolMS</h1>
        </div>
        <div style="padding:28px;">
          <p>Dear <strong>${studentName}</strong>,</p>
          <p style="color:#64748b;">Your student profile has been updated. Time: <strong>${getIndiaDateTimeString()}</strong></p>
        </div>
      </div>`
  });
};

module.exports = {
  sendPasswordResetEmail,
  sendPasswordChangedEmail,
  sendAttendanceNotification,
  sendFeePaymentNotification,
  sendSalarySlipNotification,
  sendBroadcastEmail,
  sendEmployeeWelcomeEmail,
  sendEmployeeUpdateEmail,
  sendStudentWelcomeEmail,
  sendStudentUpdateEmail,
};